logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
included-patches = "'Premium heading'"
excluded-patches = "'Alternative thumbnails' 'Append time stamps information' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom double tap length' 'Custom seekbar color' 'Enable gradient loading screen' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable wide search bar' 'Hide autoplay button' 'Hide channel avatar section' 'Hide channel profile components' 'Hide comment component' 'Hide mix playlists' 'Hide time stamp' 'Hide trending searches' 'Keep landscape mode' 'Theme' 'Translations'"

[Music]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
cli-source = "inotia00/revanced-cli" 
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
version = "auto"


[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"

[Tiktok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
cli-source = "revanced/revanced-cli" 
version = "33.3.4"
excluded-patches = "'Remember clear display'"
